const products=(window.PRODUCTS||[]).map(p=>p.offerUntil&&Date.now()>new Date(p.offerUntil).getTime()?{...p,price:p.regularPrice,regularPrice:null,featuredOffer:false}:p),money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n);
let basket=JSON.parse(localStorage.getItem('falucho-cart')||'{}'),activeCategory='all',activeSubcategory='all',query='',sortMode='featured',visibleLimit=30;
const subcategoryMenus={Alimentos:['Almacén','Lácteos y quesos','Panificados','Golosinas','Conservas','Salsas y aderezos'],Bebidas:['Sin alcohol','Con alcohol'],Limpieza:['Lavadero','Cocina','Baño','Desinfectantes','Elegante']};
const normalizedText=p=>[p.name,p.brand,p.sku,...(p.categories||[])].join(' ').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function productSubcategory(p){const t=normalizedText(p);if(p.cat==='Alimentos'){if(/queso|leche|yogur|manteca|crema|lacteo/.test(t))return 'Lácteos y quesos';if(/pan\b|pancho|hamburguesa|lactal|tostad|pascualina|empanad|talita/.test(t))return 'Panificados';if(/alfajor|chupet|rocklet|golos|caramel|chocolate|gallet|bocadito/.test(t))return 'Golosinas';if(/atun|durazno|pera gentleman|conserva|lata/.test(t))return 'Conservas';if(/mayonesa|ketchup|mostaza|salsa|aderezo|pure de tomate/.test(t))return 'Salsas y aderezos';return 'Almacén'}if(p.cat==='Bebidas'){return /agua|gaseosa|coca|sprite|baggio|jugo|fresh|speed|energizante|soda/.test(t)?'Sin alcohol':'Con alcohol'}if(p.cat==='Limpieza'){if(/elegante/.test(t))return 'Elegante';if(/jabon en polvo|jabon liquido|ariel|lavadero|ropa|suavizante/.test(t))return 'Lavadero';if(/cocina|detergente|desengras/.test(t))return 'Cocina';if(/bano/.test(t))return 'Baño';if(/desinfectante|lavandina|ayudin/.test(t))return 'Desinfectantes'}return ''}
function renderSubcategoryTabs(){const tabs=document.querySelector('#subCategoryTabs'),items=subcategoryMenus[activeCategory]||[];if(!items.length){tabs.hidden=true;tabs.innerHTML='';activeSubcategory='all';return}tabs.hidden=false;tabs.innerHTML=`<button class="active" data-subcategory="all">Todos</button>${items.map(item=>`<button data-subcategory="${item}">${item}</button>`).join('')}`;}
const packBadge=p=>{if(p.packLabel)return p.packLabel;const units=p.name.match(/\bx\s*(\d+)\s*unidades?/i);return /^Pack\b/i.test(p.name)||units?(units?`PACK X${units[1]}`:'PACK'):''};
const productFormat=p=>{if(p.cat==='Combos')return 'COMBO';const units=p.name.match(/\bx\s*(\d+)\s*unidades?/i),pack=packBadge(p);if(/^Caja\b/i.test(p.name))return units?`CAJA X${units[1]}`:'CAJA';return pack||'UNIDAD'};
const card=p=>{const pack=packBadge(p),isCombo=p.cat==='Combos',boxMessage=encodeURIComponent(`Hola, quiero consultar el precio por caja de ${p.name}.`),details=p.comboItems?.length?`<details class="comboDetails" open><summary>Incluye</summary><ul>${p.comboItems.map(item=>`<li>${item}</li>`).join('')}</ul></details>`:'';return `<article class="card">${p.regularPrice?'<span class="badge">OFERTA</span>':''}${pack?`<span class="badge">${pack}</span>`:''}<img loading="lazy" src="${p.img}" alt="${p.name}"><div class="cardBody">${p.brand?`<small class="brandName">${p.brand}</small>`:''}<h3>${p.name}</h3>${details}${p.regularPrice?`<del>${money(p.regularPrice)}</del>`:''}<small class="priceType">${isCombo?'Precio por combo':pack?'Precio por pack':'Precio unitario'}</small><div class="price">${money(p.price)}</div><span class="transfer">${money(p.price*.95)} con transferencia</span><button class="add" data-add="${p.id}">Agregar</button>${isCombo?'':`<a class="boxQuote" href="https://wa.me/541164591826?text=${boxMessage}" target="_blank" rel="noopener">Consultar precio por caja</a>`}</div></article>`};
function filteredProducts(){let list=products.filter(p=>activeCategory==='all'||(activeCategory==='Ofertas'?p.featuredOffer===true:p.cat===activeCategory));if(activeSubcategory!=='all')list=list.filter(p=>productSubcategory(p)===activeSubcategory);if(query)list=list.filter(p=>[p.name,p.cat,p.brand,p.sku,...(p.categories||[])].join(' ').toLowerCase().includes(query));if(sortMode==='price-asc')list.sort((a,b)=>a.price-b.price);if(sortMode==='price-desc')list.sort((a,b)=>b.price-a.price);if(sortMode==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'es'));return list}
function renderCatalog(){const list=filteredProducts();productGrid.innerHTML=list.length?list.slice(0,visibleLimit).map(card).join(''):`<p class="categoryEmpty">${activeCategory==='Ofertas'&&!query?'Próximamente vas a encontrar acá nuestras mejores ofertas.':'No encontramos productos con esa búsqueda.'}</p>`;resultsCount.textContent=`${list.length} ${list.length===1?'producto':'productos'}`;loadMore.hidden=list.length<=visibleLimit;clearFilters.hidden=activeCategory==='all'&&activeSubcategory==='all'&&!query&&sortMode==='featured';document.querySelector('#offersNotice').hidden=activeCategory!=='Ofertas'}
function save(){localStorage.setItem('falucho-cart',JSON.stringify(basket));renderCart()}function renderCart(){const entries=Object.entries(basket).filter(([id])=>products.some(p=>p.id==id));cartCount.textContent=entries.reduce((s,[,q])=>s+q,0);cartItems.className='cartItems';cartItems.innerHTML=entries.length?entries.map(([id,q])=>{const p=products.find(x=>x.id==id);return `<div class="cartRow"><img src="${p.img}" alt=""><div><p><b>${p.name}</b></p><small class="cartFormat">${productFormat(p)}</small><span>${money(p.price*q)}</span></div><div class="qty"><button data-qty="${id}" data-d="-1">−</button><b>${q}</b><button data-qty="${id}" data-d="1">+</button></div></div>`}).join(''):'<p class="empty">Tu carrito está vacío.</p>';cartTotal.textContent=money(entries.reduce((s,[id,q])=>s+products.find(p=>p.id==id).price*q,0))}
function openCart(v=true){document.querySelector('#cart').classList.toggle('open',v);overlay.classList.toggle('show',v);document.querySelector('#cart').setAttribute('aria-hidden',!v)}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){basket[add.dataset.add]=(basket[add.dataset.add]||0)+1;save();openCart()}const q=e.target.closest('[data-qty]');if(q){const id=q.dataset.qty;basket[id]=(basket[id]||0)+Number(q.dataset.d);if(basket[id]<=0)delete basket[id];save()}const tab=e.target.closest('[data-category]');if(tab){activeCategory=tab.dataset.category;activeSubcategory='all';visibleLimit=30;document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b===tab));renderSubcategoryTabs();renderCatalog()}const subtab=e.target.closest('[data-subcategory]');if(subtab){activeSubcategory=subtab.dataset.subcategory;visibleLimit=30;document.querySelectorAll('[data-subcategory]').forEach(b=>b.classList.toggle('active',b===subtab));renderCatalog()}});
searchBtn.onclick=()=>{document.querySelector('#catalogo').scrollIntoView();search.focus()};cartBtn.onclick=()=>openCart();closeCart.onclick=overlay.onclick=()=>openCart(false);search.oninput=e=>{query=e.target.value.trim().toLowerCase();visibleLimit=30;renderCatalog()};sort.onchange=e=>{sortMode=e.target.value;visibleLimit=30;renderCatalog()};loadMore.onclick=()=>{visibleLimit+=30;renderCatalog()};clearFilters.onclick=()=>{activeCategory='all';activeSubcategory='all';query='';sortMode='featured';search.value='';sort.value='featured';visibleLimit=30;document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category==='all'));renderSubcategoryTabs();renderCatalog()};
checkout.onclick=()=>{const entries=Object.entries(basket).filter(([id])=>products.some(p=>p.id==id));if(!entries.length)return;const lines=entries.map(([id,q])=>{const p=products.find(x=>x.id==id);return `• ${q} x ${p.name} — ${money(p.price*q)}`}),total=entries.reduce((s,[id,q])=>s+products.find(p=>p.id==id).price*q,0),msg=`Hola, quiero hacer este pedido:\n\n${lines.join('\n')}\n\nTotal estimado: ${money(total)}\n\n¿Me confirman stock, precio y envío?`;window.open(`https://wa.me/541164591826?text=${encodeURIComponent(msg)}`,'_blank')};allCount.textContent=`(${products.length})`;renderSubcategoryTabs();renderCatalog();renderCart();
